### ISSUE TITLE
Feature: configuring dependabot security updates

### ISSUE THREAD

**Issue by BoBoBaSs84** [siemens/simatic-s7-webserver-api#47]
That little robot takes care of updates concerning `github-actions` and the `nuget` package ecosystem. 

Add `dependabot.yml` with this:
```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
Should take care of it.
